config/routes.rb
Rails.application.routes.draw do

  root :to => 'pages#home'

  get '/signup' => 'users#new'
  post '/users' => 'users#create'

  get '/signin' => 'sessions#new'
  post '/signin' => 'sessions#create'
  get '/signout' => 'sessions#destroy'

  resources :users, :only => [:show]
  get '/admin' => 'users#admin'

  resources :hikes do
    resources :reviews, :except => [:index, :show]
  end

  post '/search' => 'hikes#search'

  resources :contact_forms, :only => [:new, :create]

end

app/models/account.rb
class Account < ApplicationRecord
  belongs_to :user
  has_many :reviews
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/contactform.rb
class ContactForm < MailForm::Base
  attribute :name,      :validate => true
  attribute :email,     :validate => /\A([\w\.%\+\-]+)@([\w\-]+\.)+([\w]{2,})\z/i
  attribute :message

  # Declare the e-mail headers. It accepts anything the mail method
  # in ActionMailer accepts.
  def headers
    {
      :subject => "Take A Hike - Contact Message",
      :to => "info@takeahike.com",
      :from => %("#{name}" <#{email}>)
    }
  end
end

app/models/hike.rb
class Hike < ApplicationRecord
  has_many :reviews

  has_attached_file :image, default_url: "/images/missing.png"
  validates_attachment_content_type :image, content_type: /\Aimage\/.*\z/

  scope :search, -> (keyword) { where("name ILIKE ?", "%#{keyword}%")}

end

app/models/review.rb
class Review < ApplicationRecord
  belongs_to :account
  belongs_to :hike
end

app/models/user.rb
class User < ApplicationRecord
  has_secure_password
  has_one :account

  after_create :register_account

  validates :email, uniqueness: true
  validates :email, :password, :password_confirmation, presence: true
  validates :password, format: { with: /(?=.*[a-z])(?=.*[A-Z])(?=.*\d)./,
    message: 'must include at least one lowercase letter, one uppercase letter, and one digit' }

  def register_account
    user = User.last
    Account.create!(user_id: user.id)
  end

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
  helper_method :current_user

  def current_user
    if session[:user_id]
      @current_user ||= User.find(session[:user_id])
    end
  end

  def authorize_user
    if !current_user
      redirect_to '/signin', notice: 'You must sign in to view that page.'
    end
  end

  def authorize_admin
    if !(current_user && current_user.admin)
      redirect_to '/signin', notice: 'You must be an administrator to access that page.'
    end
  end

end

app/controllers/contact_forms_controller.rb
class ContactFormsController < ApplicationController

  def new
    @contact_form = ContactForm.new
  end

  def create
    contact_form = ContactForm.new(params[:contact_form])
    contact_form.request = request
    if contact_form.deliver
      flash.now[:notice] = 'Message successfully sent.'
    else
      render :new
    end
  end

end

app/controllers/hikes_controller.rb
class HikesController < ApplicationController
  before_action :authorize_admin, :except => [:index, :show, :search]

  def index
    @hikes = Hike.all
  end

  def show
    @hike = Hike.find(params[:id])
    @lat = @hike.latitude
    @lng = @hike.longitude
    weather_object = Weather.new(@lat, @lng)
    @weather = weather_object.get_weather()
    @icon = @weather[:currently]
  end

  def new
    @hike = Hike.new
  end

  def create
    if Hike.create!(hike_params)
      redirect_to admin_path, notice: 'Hike successfully added!'
    else
      render :new
    end
  end

  def edit
    @hike = Hike.find(params[:id])
  end

  def update
    @hike = Hike.find(params[:id])
    if @hike.update!(hike_params)
      redirect_to admin_path, notice: 'Hike successfully updated!'
    else
      render :edit
    end
  end

  def destroy
    @hike = Hike.find(params[:id])
    @hike.destroy
    redirect_to admin_path, notice: 'Hike successfully deleted!'
  end

  def search
    @search_results = Hike.search(params[:search])
    render :search
  end

private

  def hike_params
    params.require(:hike).permit(:name, :length, :elevation, :difficulty, :description, :image)
  end

end

app/controllers/pages_controller.rb
class PagesController < ApplicationController

end

app/controllers/reviews_controller.rb
class ReviewsController < ApplicationController
  before_action :find_hike, :authorize_user
  after_action :update_hike_rating

  def new
    @hike = Hike.find(params[:hike_id])
    @review = Review.new
  end

  def create
    if @hike.reviews.create!(account_id: current_user.account.id, author: current_user.username, content: review_params[:content], rating: review_params[:rating])
      redirect_to hike_path(@hike), notice: 'Your review was successfully added!'
    else
      render :new
    end
  end

  def edit
    @review = Review.find(params[:id])
  end

  def update
    @review = Review.find(params[:id])
    if @review.update!(review_params)
      redirect_to hike_path(@hike), notice: 'Review successfully edited.'
    else
      render :edit
    end
  end

  def destroy
    @review = Review.find(params[:id])
    @review.destroy
    redirect_to hike_path(@hike), notice: 'Review successfully deleted.'
  end

private

  def review_params
    params.require(:review).permit(:rating, :content)
  end

  def find_hike
    @hike = Hike.find(params[:hike_id])
  end

  def update_hike_rating
    total_rating = 0
    @hike.reviews.each do |review|
      total_rating += review.rating
    end
    total_reviews = @hike.reviews.length.to_f
    updated_rating = (total_rating/total_reviews).round(1)
    @hike.update!(rating: updated_rating)
  end

end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController

  def create
    @user = User.find_by_email(params[:email])
    if @user && @user.authenticate(params[:password])
      flash[:notice] = "You've signed in."
      session[:user_id] = @user.id
      redirect_to "/"
    else
      flash[:alert] = "There was a problem signing in. Please try again."
      redirect_to "/signin"
    end
  end

  def destroy
    session[:user_id] = nil
    flash[:notice] = "You've signed out."
    redirect_to "/"
  end

end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :authorize_admin, :only => [:admin]

  def new
    @user = User.new
  end

  def create
    @user = User.new(user_params)
    if @user.save
      flash[:notice] = "You've successfully signed up!"
      session[:user_id] = @user.id
      redirect_to "/"
    else
      flash[:alert] = "There was a problem signing up."
      render :new
    end
  end

  def admin
    @hikes = Hike.all
  end

  def show
    @account = Account.find(params[:id])
    @reviews = @account.reviews
  end

private

  def user_params
    params.require(:user).permit(:email, :password, :password_confirmation, :username)
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/contact_form_helper.rb
module ContactFormHelper
end

app/views/contact_forms/create.html.erb
<body class='contact'>
  <h3>Get In Touch</h3>

  <div class="row container">
    <div class="col s12">
      <div class="card-panel" id="contact-form">
        <h4>Thank you for your message!</h4>

        <p>We'll get back to you as soon as possible.</p>

        <%= link_to 'Home', root_url, class: 'btn' %>
      </div>
    </div>
  </div>

</body>

app/views/contact_forms/new.html.erb
<body class='contact'>
  <h3>Get In Touch</h3>

  <div class="row container">
    <div class="col s12">
      <div class="card-panel" id="contact-form">
        <%= form_for @contact_form do |f| %>
          <div class='form-group'>
            Name: <%= f.text_field :name %>
          </div>
          <div class='form-group'>
            Email: <%= f.text_field :email %>
          </div>
          <div class='form-group'>
            Message: <%= f.text_area :message %>
          </div>
          <%= f.submit "Send Message", class: 'btn' %>
        <% end %>
      </div>
    </div>
  </div>

</body>

app/views/hikes/_form.html.erb
<%= render 'layouts/errors', :object => @hike %>

<%= form_for @hike do |f| %>
  <div class='form-group'>
    <%= f.label :name %>
    <br>
    <%= f.text_field :name %>
  </div>
  <div class='form-group'>
    <%= f.label :length %>
    <br>
    <%= f.text_field :length %>
  </div>
  <div class='form-group'>
    <%= f.label :elevation %>
    <br>
    <%= f.text_field :elevation %>
  </div>
  <div class='form-group'>
    <%= f.label :difficulty %>
    <br>
    <%= f.text_field :difficulty %>
  </div>
  <div class='form-group'>
    <%= f.label :description %>
    <br>
    <%= f.text_area :description %>
  </div>
  <div class='form-group'>
    <%= f.label 'Upload Picture:' %>
    <br>
    <%= f.file_field :image %>
  </div>
  <%= f.submit :class => 'btn btn-outline-success'%>
<% end %>

app/views/hikes/edit.html.erb
<h3>Update trail information for <%= @hike.name %></h3>

<%= render 'form' %>

app/views/hikes/index.html.erb
<h3>Browse All Hikes</h3>

<div class='row container-fluid'>

  <% @hikes.each do |hike| %>
    <div class="col s4 index-hike-title">
      <div class='row'>
        <div class='col s9'>
          <h5><%= link_to hike.name, hike_path(hike) %></h5>
        </div>
        <div class='col s3'>
          <p><%= hike.rating %>/5</p>
        </div>
      </div>
      <a href='/hikes/<%= hike.id %>'><%= image_tag hike.image.url, class: 'thumbnail' %></a>
    </div>
  <% end %>

</div>

app/views/hikes/new.html.erb
<h3>Add a New Hike</h3>

<%= render 'form' %>

app/views/hikes/search.html.erb
<h3>Search Results:</h3>

<ul>
  <% @search_results.each do |hike| %>
    <li><%= link_to hike.name, hike_path(hike) %></li>
  <% end %>
</ul>

app/views/hikes/show.html.erb
<div class='row'>
  <div class='col s4'>
    <h3><%= @hike.name %></h3>
  </div>
  <div class='col s2'>
    <p><canvas id="icon1" width="64" height="64"></canvas>
    <script>
      var skycons = new Skycons({"color": "royalblue"});
      skycons.add("icon1", "<%= @icon %>");
      skycons.play();
    </script></p>
    <p><%= @weather[:currently] %>, <%= @weather[:temperature] %><sup>o</sup>F</p>
  </div>
  <div class='col s2'>
    <p>Low: <%= @weather[:min] %><sup>o</sup>F</p>
    <p>High: <%= @weather[:max] %><sup>o</sup>F</p>
  </div>
  <div class='col s4' id='show-rating'>
    <h5>Average Rating: </h5>
    <% if @hike.rating == nil %>
      <h5>N/A</h5>
    <% else %>
      <h5><%= @hike.rating %>/5</h5>
    <% end %>
  </div>
</div>

<div class='row'>
  <div class='col s4'>
    <p>
      <b>Difficulty:</b>
      <%= @hike.difficulty %>
    </p>
  </div>
  <div class='col s4'>
    <p>
      <b>Distance:</b>
      <%= @hike.length %> miles
    </p>
  </div>
  <div class='col s4'>
    <p>
      <b>Elevation Gain:</b>
      <%= @hike.elevation %> feet
    </p>
  </div>
</div>

<div class='row container-fluid'>
  <div class='col s6'>
    <%= image_tag @hike.image.url, class: 'show-image' %>
  </div>
  <div class='col s6'>
    <div id="map"></div>
    <script>
      function initMap() {
        var target = {lat: <%= @lat %>, lng: <%= @lng %>};
        var map = new google.maps.Map(document.getElementById('map'), {
          zoom: 11,
          center: target
        });
        var marker = new google.maps.Marker({
          position: target,
          map: map
        });
      }
    </script>
    <script async defer
    src='https://maps.googleapis.com/maps/api/js?key=AIzaSyCCHvwf-TfXUOU12tRKjippgOfqs5iVboM&callback=initMap'>
    </script>
  </div>
</div>

<div class='row'>
  <div class='col s12'>
    <h5>Description</h5>
    <p><%= @hike.description %></p>

    <hr>

    <h5>Reviews</h5>
    <%= link_to 'Add a Review', new_hike_review_path(@hike), class: 'btn btn-outline-primary' %>
  </div>
</div>


<% @hike.reviews.each do |review| %>
  <div class="card container">
    <div class="card-content blue lighten-5">

      <div class="row">
        <div class="col s6">
          <big><p><%= review.author %></p></big>
        </div>
        <div class="col s6" id="review-rating">
          <%= review.rating %>/5
          <br>
          <%= review.created_at %>
        </div>
      </div><!-- row -->

      <div class="divider"></div>
      <div class="card-action">
        <p class="card-text"><%= review.content %></p>
        <br>
        <% if current_user && (review.account_id == current_user.account.id) %>
          <%= link_to 'Edit', edit_hike_review_path(@hike, review), class: 'card-link light-blue-text text-darken-3' %>
        <% end %>
        <% if current_user && (review.account_id == current_user.account.id || current_user.admin) %>
          <%= link_to 'Delete', hike_review_path(@hike, review), method: 'delete', data: { confirm: 'Are you sure you want to delete your review?' }, class: 'card-link light-blue-text text-darken-3' %>
        <% end %>
      </div><!-- card-action -->

    </div><!-- card-content -->
  </div><!-- card -->
<% end %>

app/views/layouts/_errors.html.erb
<% if object.errors.any? %>
  <div id='errors' class='container card'>
    <h3>Please fix these errors:</h3>
    <ul>
      <% object.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
    </ul>
  </div>
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Take A Hike</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
    <link href="https://fonts.googleapis.com/icon?family=Material+Icons" rel="stylesheet">
    <link href="//netdna.bootstrapcdn.com/font-awesome/3.2.1/css/font-awesome.css" rel="stylesheet">
    <script src="https://gitcdn.link/cdn/darkskyapp/skycons/master/skycons.js"></script>

  </head>

  <body>

    <nav class="nav-extended">
      <div class="nav-wrapper">
        <ul class="left hide-on-med-and-down">
          <li><a href="/">HOME</a></li>
          <li><a class="active" href="/hikes">HIKES</a></li>
          <li><a href="/contact_forms/new">CONTACT</a></li>
        </ul>
        <a href="/" class="brand-logo center">Take A Hike</a>
        <ul id="nav-mobile" class="right hide-on-med-and-down">
          <% if !current_user %>
          <li><a href="/signup">REGISTER</a></li>
          <li><a href="/signin">SIGN IN</a></li>
          <% else %>
          <li><a href="/users/<%= current_user.id %>"><%= current_user.email %></a></li>
          <li><a class="nav-link" href="/signout">SIGN OUT</a></li>
          <% end %>
        </ul>
      </div>
    </nav>

    <%= flash[:alert] %>
    <%= flash[:notice] %>

    <main>
      <div class='row'>
        <div class='col s12'>
          <%= yield %>
        </div>
      </div>
    </main>

    <footer class="page-footer">
      <div class="container">
        <div class="row">
          <div class="col l6 s12">
            <h5 class="white-text">Take A Hike</h5>
            <p class="grey-text text-lighten-4">Exploring the PNW one hike at a time.</p>
          </div>
          <div class="col l4 offset-l2 s12">
            <h5 class="white-text">Links</h5>
            <ul>
              <li><a class="grey-text text-lighten-3" href="/">Home</a></li>
              <li><a class="grey-text text-lighten-3" href="/hikes">Hikes</a></li>
              <li><a class="grey-text text-lighten-3" href="/contact_forms/new">Contact</a></li>
            </ul>
          </div>
        </div>
      </div>
      <div class="footer-copyright">
        <div class="container">
          © 2017 Bryan Lin
          <% if current_user && current_user.admin %>
          <a class="grey-text text-lighten-4 right" href="/admin">Admin</a>
          <% end %>
        </div>
      </div>
    </footer>

  </body>

</html>

app/views/pages/home.html.erb
<body id='home'>
  <h2>Explore the Beautiful Pacific Northwest</h2>

  <div class='container section' id='home-search'>
    <h4>Find your next adventure:</h4>
    <%= form_tag (search_path), class:'form-inline my-2 my-lg-0' do %>
      <%= text_field_tag :search, "", class: 'form-control mr-sm-2' %>
      <%= submit_tag 'Search', class: 'btn my-2 my-sm-0 nav-btn' %>
    <% end %>
  </div>
</body>

app/views/reviews/_form.html.erb
<%= render 'layouts/errors', :object => @review %>

<%= form_for [@hike, @review] do |f| %>
  <div class='form-group'>
    <%= f.label :rating %>
    <br>
    <%= f.number_field :rating, in: 1..5 %>
  </div>
  <div class='form-group'>
    <%= f.label :content %>
    <br>
    <%= f.text_area :content %>
  </div>
  <%= f.submit :class => 'btn btn-outline-success'%>
<% end %>

app/views/reviews/edit.html.erb
<h3>Add Your Review for <%= @hike.name %></h3>

<%= render 'form' %>

app/views/reviews/new.html.erb
<h3>Add a Review for <%= @hike.name %></h3>

<%= render 'form' %>

app/views/users/admin.html.erb
<h3>Administrator Controls</h3>

<h5>Hikes Directory:</h5>

<ul>
  <% @hikes.each do |hike| %>
    <li>
      <%= link_to hike.name, hike_path(hike) %>
      <%= link_to 'Update', edit_hike_path(hike), class: 'teal btn-flat' %>
      <%= link_to 'Delete', hike_path(hike), method: 'delete', data: { confirm: 'Are you sure you want to remove this hike?' }, class: 'red btn-flat' %>
    </li>
    <br>
  <% end %>
</ul>



<%= link_to 'Add New Hike', new_hike_path, class: 'btn btn-outline-primary' %>

app/views/users/home.html.erb
<body id='home-welcome'>
  <h2>Hiking the Beautiful Pacific Northwest</h2>

  <div class='container section' id='home-search'>
    <h4>Find your next adventure:</h4>
    <%= form_tag (search_path), class:'form-inline my-2 my-lg-0' do %>
      <%= text_field_tag :search, "", class: 'form-control mr-sm-2' %>
      <%= submit_tag 'Search', class: 'btn my-2 my-sm-0 nav-btn' %>
    <% end %>
  </div>
</body>

app/views/users/new.html.erb
<div class="container">
  <h3>Sign Up</h3>

  <%= render 'layouts/errors', :object => @user %>

  <%= form_for @user do |f| %>
    <div class="form-group">
      <%= f.label 'Username' %>
      <br>
      <%= f.text_field :username %>
    </div>
    <div class="form-group">
      <%= f.label 'Email' %>
      <br>
      <%= f.text_field :email %>
    </div>
    <div class="form-group">
      <%= f.label 'Password' %>
      <br>
      <%= f.password_field :password %>
    </div>
    <div class="form-group">
      <%= f.label :password_confirmation %>
      <br>
      <%= f.password_field :password_confirmation %>
    </div>
    <%= f.submit 'Sign Up', class: 'btn btn-outline-success' %>
  <% end %>
</div>

app/views/users/show.html.erb
<h3><%= current_user.email %></h3>

<hr>

<h5>All Reviews:</h5>

<ul>
  <% @reviews.each do |review| %>
    <li><%= link_to review.hike.name, hike_path(review.hike) %> (<%= review.rating %>/5)</li>
  <% end %>
</ul>